[exports.locations]
auto = false
exporter = "locations"
path = ".bacon-locations"
line_format = "{kind} {path}:{line}:{column} {message}"


# If you want some job to emit a beep on success or on failure,
# you need to globally enable sound, and you may set up the max volume here
#
# With sound enabled, you may set up sound on a job with eg
#    on_success = "play-sound(name=90s-game-ui-6,volume=50)"
#    on_failure = "play-sound(name=beep-warning,volume=100)"
[sound]
enabled = false # set true to allow sound
base_volume = "100%" # global volume multiplier

[jobs.bacon-ls]
command = [
  "cargo", "clippy", "--target=wasm32-unknown-unknown", "--all-features",
  "--message-format", "json-diagnostic-rendered-ansi",
]
analyzer = "cargo_json"
need_stdout = true

[jobs.bacon-ls.env]
CARGO_TARGET_DIR = "./target/bacon-ls"

[exports.cargo-json-spans]
auto = true
exporter = "analyzer"
line_format = """\
  {diagnostic.level}|:|{span.file_name}|:|{span.line_start}|:|{span.line_end}|:|\
  {span.column_start}|:|{span.column_end}|:|{diagnostic.message}|:|{diagnostic.rendered}|:|\
  {span.suggested_replacement}\
"""
path = ".bacon-locations"
